"""The shelley-managed shpc settings file.

shpc's own defaults put every install base under ``$HOME`` — ``module_base:
$HOME/shpc/modules`` and friends. Because the build path re-execs under ``sudo -E``,
which preserves ``HOME``, that means root writes the modules into the *invoking user's*
home directory, where no other user can read them. shelley therefore pins the four base
paths itself.

The mechanism is shpc's global ``--settings-file`` flag. shpc's loader reads its packaged
defaults first and then ``dict.update()``s the named file over them, so this file only
needs to carry the keys shelley overrides, and it inherits future upstream defaults for
everything else. ``--settings-file`` is also the highest-precedence layer, above
``~/.singularity-hpc/settings.yml``, so a per-user shpc config cannot redirect a shared
build.

Deliberately subprocess-free. ``shpc config set/add`` would work, but its ``save()``
writes the whole *merged* settings dict, freezing today's site defaults into what is
meant to be a small override file.
"""

import logging
import os
import tempfile
from pathlib import Path

import yaml

from ..utils.globals import (
    SHARED_FILE_MODE,
    UPSTREAM_SHPC_REGISTRY,
    local_registry,
    shpc_container_base,
    shpc_module_base,
    shpc_settings_file,
    shpc_views_base,
    shpc_wrapper_base,
)

log = logging.getLogger(__name__)

_HEADER = (
    "# Managed by shelley — do not edit.\n"
    "# Regenerated by `shelley build`; shpc merges these over its own defaults.\n"
)


def desired_registry() -> list[str]:
    """The registry search path: shelley's local entries first, then upstream.

    Order is honoured by shpc, and local must come first so that a locally authored
    container.yaml (the interactive-alias and missing-tag paths) shadows the upstream
    entry for the same tool.

    A filesystem registry path that does not exist makes shpc raise ValueError on
    *every* command, including `config get` — Filesystem.matches() is a bare
    os.path.exists and Registry.__init__ resolves the whole list eagerly. So the local
    entry is dropped rather than risk bricking shpc; ensure_shared_layout() normally
    creates it first.
    """
    local = local_registry()
    if not local.is_dir():
        log.debug("Omitting %s from the shpc registry list: not a directory", local)
        return [UPSTREAM_SHPC_REGISTRY]
    return [str(local), UPSTREAM_SHPC_REGISTRY]


def desired_settings() -> dict:
    """The settings shelley overrides — absolute paths only, never $HOME."""
    return {
        "module_base": str(shpc_module_base()),
        "container_base": str(shpc_container_base()),
        "wrapper_base": str(shpc_wrapper_base()),
        "views_base": str(shpc_views_base()),
        "registry": desired_registry(),
    }


def _read(path: Path) -> dict | None:
    try:
        with open(path) as f:
            return yaml.safe_load(f)
    except (OSError, yaml.YAMLError) as e:
        log.debug("Could not read %s: %s", path, e)
        return None


def ensure_shared_shpc_settings() -> Path:
    """Write the shared shpc settings file if it is missing or stale.

    Idempotent: an already-correct file is left untouched, mtime included. Raises
    RuntimeError on failure — the build path must not fall back to shpc's $HOME
    defaults, which is the very bug this file exists to prevent.
    """
    path = shpc_settings_file()
    wanted = desired_settings()

    if path.is_file() and _read(path) == wanted:
        return path

    body = _HEADER + yaml.dump(wanted, default_flow_style=False, sort_keys=False)

    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        # Write via a temp file in the same directory so a concurrent build never
        # observes a half-written settings file.
        fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".settings-", suffix=".yml")
        try:
            with os.fdopen(fd, "w") as f:
                f.write(body)
            os.chmod(tmp, SHARED_FILE_MODE)
            os.replace(tmp, path)
        except BaseException:
            os.unlink(tmp)
            raise
    except OSError as e:
        raise RuntimeError(
            f"Could not write the shared shpc settings file {path}: {e}. "
            f"Without it shpc installs into $HOME, where other users cannot read it. "
            f"Re-run with sudo, or set SHELLEY_SHPC_BASE to a writable location."
        ) from e

    log.info("Wrote shared shpc settings to %s", path)
    return path
